version: "2.1"
services:
  transmission:
    image: gists/transmission:3.00
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guayaquil
      - USERNAME=username
      - PASSWORD=password
    volumes:
      - <path to data>:/config/config
      - <path to downloads>:/downloads/downloads
      - <path to watch folder>:/watch/watch
    ports:
      - 80:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always